### ISSUE TITLE
is the model_ref need set app_label='mutant'

### ISSUE THREAD

**Issue by caoguangyao** [charettes/django-mutant#48]
hi charettes:

I use the following code to define my dynamic model 

```python
from mutant.contrib.text.models import CharFieldDefinition
from mutant.models.model import ModelDefinition

def home_view(request):
    model_def = ModelDefinition.objects.create(
        app_label='app',
        object_name='MyOtherModel',
    )
    char_field = CharFieldDefinition.objects.create(
        name='char_field',
        max_length=25,
        model_def=model_def
    )
    OtherModel = model_def.model_class()
    OtherModel.objects.create(char_field='hello world')
    queryset = OtherModel.objects.all()
    d = serializers.serialize('json',queryset)
    return HttpResponse(d) 
```

it gives the UNIQUE constraint failed
but when I set app_label='mutant' ,it works fine.
Does app_label need hard coded?

**Comment by charettes** [comment]
@caoguangyao it's hard to tell without the actual traceback but I suppose you're creating a `ModelDefinition` everytime the view is accessed. `ModelDefinition` has a unique constraint on `app_label` and `object_name` which prevents duplicate model definitions. You might want to use `get_or_create` instead of `create` and only create the `CharField` definition if the `model_def` was created. Something like the following should do:

```python
model_def = ModelDefinition.objects.get_or_create(
    app_label='app',
    object_name='MyOtherModel',
    defaults={'fields': [CharFieldDefinition(name='char_field', max_length=25)])
)
```

**Comment by caoguangyao** [comment]
yes,I forget refresh the data and  created it many times
